name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ✅ Allows pushing to gh-pages
      pages: write      # ✅ Required for GitHub Pages
      id-token: write   # ✅ Needed for authentication

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.VITE_SUPABASE_SERVICE_ROLE_KEY }}
          VITE_PGVECTOR_DIMS: ${{ secrets.VITE_PGVECTOR_DIMS }}
          # If you need VITE_SUPABASE_DB_URL, add it here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # ✅ Ensure this matches your actual build output directory

